### ISSUE TITLE
error on icon click

### ISSUE THREAD

**Issue by Gennady-G** [XigeTime/FontAwesome-Selector#1]
Hi!

have an error in Chrome ( v. 83.0.4103.97, (64-bit)), on double-click. When opened demo page with Live Server in VS:

> VM77:62 Uncaught TypeError: (event.target.className || "").indexOf is not a function
>     at onDoubleClick (eval at success (kernel.js:210), <anonymous>:62:48)
>     at dispatch (jquery.js:5237)
>     at elemData.handle (jquery.js:5044)

Also there is no text in select field, when single-clicked. Not sure how it should work..
![err-2-2020-06-15_160334](https://user-images.githubusercontent.com/5569346/84655283-c4472580-af21-11ea-9a41-640302741091.png)

**Comment by XigeTime** [comment]
Hey buddy, sorry for the late response here, this repo/package isn't really supported nor released :)

For your issue though, it looks like `event.target.className` is returning undefined, which indexOf cannot be used on, this must be a string.

When referencing event.target, if event.target is not defined, it's going to throw an error rather than assign your empty string, alternatively you could do something like this to make sure event.target is defined before trying to use it:
```
var className = event && event.target ? event.target.className : "";
if (className.indexOf(ke.getPrefix()) > -1) return;
```
